#theme: jekyll-theme-time-machine
remote_theme: daattali/beautiful-jekyll@6.0.1
title: "RAIS Codebooks"
author: "Heloisa de Paula"
cover-img: /LDIimage_11.22.19_FINALv1.jpg
gh-repo: labordynamicsinstitute/rais_codebooks
navbar-links:
  "Main" : https://labordynamicsinstitute.github.io/
  "Access at Cornell": https://labordynamicsinstitute.github.io/data-rais
  "Codebooks": 
    - 2004: output/codebook_2004.html
    - 2005: output/codebook_2005.html
    - 2006: output/codebook_2006.html
    - 2007: output/codebook_2007.html
    - 2008: output/codebook_2008.html
    - 2009: output/codebook_2009.html
    - 2010: output/codebook_2010.html
    - 2011: output/codebook_2011.html
    - 2012: output/codebook_2012.html
    - 2013: output/codebook_2013.html
    - 2014: output/codebook_2014.html
    - 2015: output/codebook_2015.html
    - 2016: output/codebook_2016.html
    - 2017: output/codebook_2017.html
  "RAIS no Brasil":  https://www.rais.gov.br/sitio/index.jsf

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
#share-links-active:
#  twitter: true
#  facebook: true
#  linkedin: true
#  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true


plugins:
  - jekyll-paginate
  - jekyll-sitemap
